### ISSUE TITLE
One failure appears to break the -a option

### ISSUE THREAD

**Issue by LeeLammert** [CiscoCloud/distributive-rpm#7]
When running distributive -a="/etc/distributive.d/, .. the first failure in a check appears to terminate the chain. Is this the expected operation?

**Comment by siddharthist** [comment]
My default behavior so far is that if the configuration is messed up, the whole program ends and outputs a message as to why, instead of trying to handle the error and move on. I think configuration errors can be considered fatal, because they have to be fixed for Distributive to be outputting useful/correct information.
